name: QuestEngine
main: com.gmail.bobason01.questengine.QuestEnginePlugin
version: 8.0
api-version: 1.18
author: crston
softdepend:
  - PlaceholderAPI
  - Vault
commands:
  quest:
    description: Player quest command
    usage: /quest
    aliases: [quests]
    permission: questengine.player
  questadmin:
    description: Admin quest command
    usage: /questadmin
    permission: questengine.admin
  questengine:
    description: Dev command
    usage: /questengine
    permission: questengine.dev
  questeditor:
    description: Opens the Quest Editor GUI for creating and editing quests.
    usage: /questeditor
    aliases: [qedit, qed, qeditor]
    permission: questengine.editor
    permission-message: §cYou are not allowed to edit quests.
permissions:
  questengine.player:
    default: true
  questengine.admin:
    default: op
  questengine.dev:
    default: op
  questengine.editor:
    description: Allows access to the in-game Quest Editor.
    default: op